/*
 * generated by Xtext 2.20.0
 */
package net.sf.orcc.cal


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CalStandaloneSetup extends CalStandaloneSetupGenerated {

	def static void doSetup() {
		new CalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
