#!/bin/sh
# 
# Simple script to switch between several versions of LLVM.
#
C='Copyright 2012 IRISA'
V='Version 0.1'
D='16 may 2011'
U='http://orcc.sourceforge.net'
# 
# Requires that you have installed the different versions of LLVM in a
# common folder.
#

LLVM_PATH=path/to/llvm

help () {
    cat <<EOF

Usage: llvm-switch version_number

This script switches the current version of LLVM in your system. It
assumes that you have installed all the LLVM versions in the same 
folder.

COPYRIGHT
  $C
VERSION
  $V ($D)
AUTHOR
  Hervé Yviquel <elldekaa@gmail.com>
  $U

EOF
    exit 0
}

if [ $# -eq 1 ]; then
	SUB_LLVM_PATH=${LLVM_PATH}/$1
	
	if [ ! -e "${SUB_LLVM_PATH}" ]; then
		echo ${SUB_LLVM_PATH} does not exist.
		help
		exit 1
	elif [ ! -d "${SUB_LLVM_PATH}" ]; then
		echo ${SUB_LLVM_PATH} is not a folder.
		help
		exit 1
	else
		export LD_LIBRARY_PATH=${SUB_LLVM_PATH}/lib:$LD_LIBRARY_PATH
		export PATH=${SUB_LLVM_PATH}/bin:$PATH	
		exit 0
	fi
else
	help
	exit 1
fi
