/*
 * generated by Xtext
 */
package net.sf.orcc.cal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.ILocationInFileProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CalUiModule extends net.sf.orcc.cal.ui.AbstractCalUiModule {

	public CalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider() {
		return CalLocationProvider.class;
	}

}
