/*
* generated by Xtext
*/
package net.sf.orcc.contentassist;

import net.sf.orcc.contentassist.AbstractCalProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CalProposalProvider extends AbstractCalProposalProvider {

}
