/*
 * Copyright (c) 2009, IETR/INSA of Rennes
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *   * Neither the name of the IETR/INSA of Rennes nor the names of its
 *     contributors may be used to endorse or promote products derived from this
 *     software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

// for MSVC
#define _CRT_SECURE_NO_DEPRECATE
#define _CRT_NONSTDC_NO_WARNINGS

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "util.h"
#include "options.h"
#include "trace.h"

// define to 1 if your system has the termios.h header
#define HAS_TERMIOS 0

#ifdef _WIN32
	#include <conio.h>
#else
	#if HAS_TERMIOS
		#include <termios.h>
	#endif
#endif

extern char *optarg;
extern int getopt(int nargc, char * const *nargv, const char *ostr);

// Directory for input files.
char *input_directory = NULL;

// input file
char *input_file;

// output YUV file
char *yuv_file;

// Profiling file
char *profiling_file;

// write file
char *write_file;

// mapping file
char *mapping_file;

// deactivate display
char display_flags = DISPLAY_ENABLE;

// compute number of errors in the program
int compareErrors = 0;

// Nb times the input file is read
int nbLoops = DEFAULT_INFINITE; // -1: infinite loop.

// Nb frames to display
int nbFrames = DEFAULT_INFINITE;

// Number of executing threads to create
int nbThreads = 1;

// Strategy for the actor mapping
int mapping_strategy = 0;

// Number of frames to display before remapping application
int nbProfiledFrames = 10;

// Repetition of the actor remapping
int mapping_repetition = REMAP_ONCE;

// Pause function
void wait_for_key() {
#ifdef _WIN32
	printf("Press a key to continue\n");
	_getch();
#else
	#if HAS_TERMIOS
		// the user has termios.h
		struct termios oldT, newT;
		char c;

		printf("Press a key to continue\n");

		// save current terminal mode
		ioctl(0, TCGETS, &oldT);

		// echo off, echo newline off, canonical mode off, 
		// extended input processing off, signal chars off
		newT.c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN | ISIG);

		ioctl(0, TCSETS, &newT); // set new terminal mode
		read(0, &c, 1); // read 1 char at a time from stdin
		ioctl(0, TCSETS, &oldT); // restore previous terminal mode
	#else
		// just revert to standard getc
		printf("Press Enter to continue\n");
		getc(stdin);
	#endif
#endif
}

void press_a_key(int code) {
    char buf[2];
    char *ptrBuff = NULL;

    printf("Press a key to continue\n");
    ptrBuff = fgets(buf, 2, stdin);
    if (ptrBuff == NULL) {
        fprintf(stderr, "error when using fgets\n");
    }
    exit(code);
}


static char *program;
static const char *usage =
    "Dataflow program generated by Orcc -- See orcc.sf.net for more information\n"

    "\nUsage: %s [options]\n"

    "\nCommon arguments:\n"
    "-i <file>          Specify an input file.\n"
    "-v <level>         Set the verbosity."
    "-h                 Print this message.\n"
    // "-t <trace directory>       Specify an output directory for the FIFO trace files.\n"

    "\nVideo-specific arguments:\n"
    "-f <nb frames>     Set the number of frames to decode before exiting.\n"
    "-n                 Ensure that the display will not be initialized (useful on non-graphic terminals).\n"
    "-o <file>          Check the output stream with the reference file specified in argument (usually YUV).\n"

    "\nRuntime arguments:\n"
    "-m <file>          Define a predefined actor mapping on multi-core platforms using the given XML file.\n"
    "-c <nb cores>      Specify the number of processor cores to use.\n"
    "-s <strategy>      Specify the run-time actor mapping strategy.\n"
    "-p <file>          Filename to write the profiling information.\n"

    "\nOther specific arguments:\n"
	"Depending on how the application has been designed, one of these arguments can be used.\n"
    "-l <nb loops>      Set the number of readings of the input file before exiting.\n"
    "-d <directory>     Set the path when multiple input files are required.\n"
    "-w <file>          Specify a file to write the output stream.\n";

void print_usage() {
	printf(usage, program);
	fflush(stdout);
}

/////////////////////////////////////
// initializes APR and parses options
void init_orcc(int argc, char *argv[]) {
	// every command line option must be followed by ':' if it takes an
	// argument, and '::' if this argument is optional
    const char *ostr = "i:no:d:m:f:w:l:r:ac:s:v:p:h";
    int c;

	program = argv[0];
	
	while ((c = getopt(argc, argv, ostr)) != -1) {
		switch (c) {
		case '?': // BADCH
            print_orcc_error(ORCC_ERR_BAD_ARGS);
            print_usage();
            exit(ORCC_ERR_BAD_ARGS);
		case ':': // BADARG
            print_orcc_error(ORCC_ERR_BAD_ARGS);
            print_usage();
            exit(ORCC_ERR_BAD_ARGS);
		case 'd':
			input_directory = strdup(optarg);
            break;
		case 'i':
			input_file = strdup(optarg);
			break;
		case 'l':
			nbLoops = strtoul(optarg, NULL, 10);
			break;
		case 'f':
			nbFrames = strtoul(optarg, NULL, 10);
            break;
        case 'c':
            nbThreads = strtoul(optarg, NULL, 10);
            break;
        case 's':
            mapping_strategy = strtoul(optarg, NULL, 10);
            break;
		case 'm':
			mapping_file = strdup(optarg);
			break;
        case 'r':
            nbProfiledFrames = strtoul(optarg, NULL, 10);
            break;
        case 'a':
            mapping_repetition = REMAP_ALWAYS;
            break;
		case 'n':
			display_flags = DISPLAY_DISABLE;
			break;
		case 'o':
			yuv_file = strdup(optarg);
			break;
		case 'w':
			write_file = strdup(optarg);
			break;
        case 'p':
            profiling_file = strdup(optarg);
            break;
        case 'v':
            set_trace_level(strtoul(optarg, NULL, 10));
            break;
        case 'h':
            print_usage();
            exit(ORCC_OK);
        default:
            print_orcc_error(ORCC_ERR_BAD_ARGS);
            print_usage();
            exit(ORCC_ERR_BAD_ARGS);
		}
	}
}
