<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ir" nsURI="http://orcc.sf.net/backends/ir" nsPrefix="net.sf.orcc.backends.ir">
  <eClassifiers xsi:type="ecore:EClass" name="InstAssignIndex" eSuperTypes="../../net.sf.orcc.core/model/Ir.ecore#//InstSpecific">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Expression" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Def"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listType" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Type"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstCast" eSuperTypes="../../net.sf.orcc.core/model/Ir.ecore#//InstSpecific">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Def"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Use"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstTernary" eSuperTypes="../../net.sf.orcc.core/model/Ir.ecore#//InstSpecific">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionValue" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Expression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trueValue" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Expression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falseValue" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Expression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Def"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockFor" eSuperTypes="../../net.sf.orcc.core/model/Ir.ecore#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinBlock" eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//BlockBasic"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" ordered="false" upperBound="-1"
        eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" ordered="false" upperBound="-1"
        eType="ecore:EClass ../../net.sf.orcc.core/model/Ir.ecore#//Instruction" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
