<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecture" nsURI="http://orcc.sf.net/backends/tta/architecture/TTA_architecture"
    nsPrefix="net.sf.orcc.backends.tta.architecture">
  <eClassifiers xsi:type="ecore:EClass" name="Design" eSuperTypes="../../net.sf.orcc.models/model/Graph.ecore#//Graph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processors" upperBound="-1"
        eType="#//Processor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedMemories" upperBound="-1"
        eType="#//Memory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareDatabase" upperBound="-1"
        eType="#//TypeToImplMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true" eSuperTypes="../../net.sf.orcc.models/model/Graph.ecore#//Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="../../net.sf.orcc.models/model/Graph.ecore#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Port" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="../../net.sf.orcc.models/model/Graph.ecore#//Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Memory" eSuperTypes="#//Link">
    <eOperations name="isShared" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wordWidth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="32"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addrWidth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedConnections" upperBound="-1"
        eType="ecore:EClass ../../net.sf.orcc.core/model/Df.ecore#//Connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processor" eSuperTypes="#//Component">
    <eOperations name="connect" eType="#//FunctionUnit">
      <eParameters name="sharedMemory" eType="#//Memory"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gcu" eType="#//GlobalControlUnit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buses" upperBound="-1"
        eType="#//Bus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bridges" upperBound="-1"
        eType="#//Bridge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sockets" upperBound="-1"
        eType="#//Socket" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionUnits" upperBound="-1"
        eType="#//FunctionUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registerFiles" upperBound="-1"
        eType="#//RegisterFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ROM" eType="#//Memory"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localRAMs" upperBound="-1"
        eType="#//Memory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedRAMs" upperBound="-1"
        eType="#//Memory" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedActors" upperBound="-1"
        eType="ecore:EClass ../../net.sf.orcc.core/model/Df.ecore#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configuration" eType="#//ProcessorConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessorConfiguration">
    <eLiterals name="Standard"/>
    <eLiterals name="Custom" value="1"/>
    <eLiterals name="Huge" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guards" upperBound="-1"
        eType="#//Guard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shortImmediate" eType="#//ShortImmediate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bridge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputBus" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputBus" eType="#//Bus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eOperations name="getBus" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalControlUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//FuPort" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnAddress" eType="#//FuPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addressSpace" eType="#//Memory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delaySlots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardLatency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionUnit" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//FuPort" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addressSpace" eType="#//Memory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegisterFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxReads" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxWrites" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//FuPort" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuPort">
    <eOperations name="connect">
      <eParameters name="socket" eType="#//Socket"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputSocket" eType="#//Socket"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputSocket" eType="#//Socket"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcodeSelector" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Socket">
    <eOperations name="isInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isOutput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedSegments" upperBound="-1"
        eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SocketType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eOperations name="getPorts" upperBound="-1" eType="#//FuPort"/>
    <eOperations name="getPortToIndexMap" upperBound="-1" eType="#//PortToIndexMapEntry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeline" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="control" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" interface="true">
    <eOperations name="isReads" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isWrites" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isResource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startCycle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cycles" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reads" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//FuPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Writes" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//FuPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShortImmediate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="#//Extension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard" abstract="true" interface="true">
    <eOperations name="isExprUnary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isExprBinary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isExprTrue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isExprFalse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprUnary" eSuperTypes="#//Guard">
    <eOperations name="isInverted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isSimple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OpUnary"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprBinary" eSuperTypes="#//Guard">
    <eOperations name="isOr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isAnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OpBinary"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e1" eType="#//ExprUnary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e2" eType="#//ExprUnary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExprTrue" eSuperTypes="#//Guard"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExprFalse" eSuperTypes="#//Guard"/>
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" interface="true">
    <eOperations name="isTermBool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isTermUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermBool" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="register" eType="#//RegisterFile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermUnit" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionUnit" eType="#//FunctionUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//FuPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implementation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hdbFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SocketType">
    <eLiterals name="input"/>
    <eLiterals name="output" value="1" literal="output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Extension">
    <eLiterals name="sign" literal="sign"/>
    <eLiterals name="zero" value="1" literal="zero"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpUnary">
    <eLiterals name="simple"/>
    <eLiterals name="inverted" value="1" literal=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpBinary">
    <eLiterals name="and"/>
    <eLiterals name="or" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeToImplMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Implementation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortToIndexMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//FuPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
</ecore:EPackage>
