<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecture"
    nsURI="http://orcc.sf.net/backends/tta/architecture/TTA_architecture" nsPrefix="net.sf.orcc.backends.tta.architecture">
  <eClassifiers xsi:type="ecore:EClass" name="TTA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buses" upperBound="-1"
        eType="#//Bus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sockets" upperBound="-1"
        eType="#//Socket" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalUnits" upperBound="-1"
        eType="#//FunctionalUnit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Socket"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalUnit"/>
</ecore:EPackage>
