<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="entities"
    nsURI="http://orcc.sf.net/backends/cplusplus/entities/YaceEntities" nsPrefix="net.sf.orcc.backends.cplusplus.entities">
  <eClassifiers xsi:type="ecore:EClass" name="Sender" eSuperTypes="#//Communicator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="ecore:EClass ../../net.sf.orcc.core/model/Df.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Receiver" eSuperTypes="#//Communicator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="ecore:EClass ../../net.sf.orcc.core/model/Df.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceEthernet" eSuperTypes="#//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communicator" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intf" eType="#//Interface"/>
  </eClassifiers>
</ecore:EPackage>
