/*
 * generated by Xtext
 */
package net.sf.orcc;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CalRuntimeModule extends net.sf.orcc.AbstractCalRuntimeModule {

}
