/*
 * generated by Xtext
 */
package net.sf.orcc.outline;

import org.eclipse.xtext.ui.common.editor.outline.actions.DefaultContentOutlineNodeAdapterFactory;

public class CalOutlineNodeAdapterFactory extends
		DefaultContentOutlineNodeAdapterFactory {

	@SuppressWarnings("unchecked")
	private static final Class[] types = {
	// provide list of classes to adapt to, e.g.:
	// Entity.class
	// Service.class
	};

	@Override
	@SuppressWarnings("unchecked")
	public Class[] getAdapterList() {
		return types;
	}

}
