/*
 * generated by Xtext
 */
package net.sf.orcc.outline;

import java.util.List;

import net.sf.orcc.cal.Action;
import net.sf.orcc.cal.Actor;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.common.editor.outline.ContentOutlineNode;
import org.eclipse.xtext.ui.common.editor.outline.CreateNode;
import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CalTransformer extends AbstractDeclarativeSemanticModelTransformer {

	@CreateNode
	public ContentOutlineNode createNode(Actor actor,
			ContentOutlineNode parentNode) {
		ContentOutlineNode node = super.newOutlineNode(actor, parentNode);

		createNodes(node, "Parameters", actor.getParameters());
		createNodes(node, "Input ports", actor.getInputs());
		createNodes(node, "Output ports", actor.getOutputs());
		createNodes(node, "State variables", actor.getStateVariables());
		createNodes(node, "Actions", actor.getActions());

		return node;
	}

	private void createNodes(ContentOutlineNode parent, String name,
			EList<?> objects) {
		ContentOutlineNode node = new ContentOutlineNode(name);
		parent.addChildren(node);
		for (Object obj : objects) {
			createNode((EObject) obj, node);
		}
	}

	public List<EObject> getChildren(Action action) {
		return NO_CHILDREN;
	}

	public List<EObject> getChildren(Actor actor) {
		return NO_CHILDREN;
	}

}
