/*
 * generated by Xtext 2.20.0
 */
package net.sf.orcc.cal.tests

import com.google.inject.Inject
import net.sf.orcc.cal.cal.AstEntity
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CalInjectorProvider)
class CalParsingTest {
	@Inject
	ParseHelper<AstEntity> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
