/*
 * generated by Xtext
 */
package net.sf.orcc.formatting;

import net.sf.orcc.services.CalGrammarAccess;
import net.sf.orcc.services.CalGrammarAccess.ActionElements;
import net.sf.orcc.services.CalGrammarAccess.ActorElements;
import net.sf.orcc.services.CalGrammarAccess.FunctionElements;
import net.sf.orcc.services.CalGrammarAccess.IfExpressionElements;
import net.sf.orcc.services.CalGrammarAccess.IntTypeElements;
import net.sf.orcc.services.CalGrammarAccess.PriorityElements;
import net.sf.orcc.services.CalGrammarAccess.ScheduleElements;
import net.sf.orcc.services.CalGrammarAccess.StateVariableElements;
import net.sf.orcc.services.CalGrammarAccess.UintTypeElements;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class CalFormatter extends AbstractDeclarativeFormatter {

	private CalGrammarAccess f;

	private void configureAction(FormattingConfig c) {
		ActionElements access = f.getActionAccess();

		c.setLinewrap().before(access.getTagAssignment_0_0());
		c.setNoSpace().before(access.getColonKeyword_0_1());

		configureActionInputs(c);
		configureActionOutputs(c);

		// action indents
		c.setIndentation(access.getActionKeyword_1(), null);

		// "guard" unindents
		c.setIndentation(null, access.getGuardKeyword_5_0());

		// "guard" indents, configure comma rules
		keywordAndCommas(c, access.getGuardKeyword_5_0(), access
				.getCommaKeyword_5_2_0());

		// "var" unindents
		c.setIndentation(null, access.getVarKeyword_6_0());

		// "var" indents, configure comma rules
		keywordAndCommas(c, access.getVarKeyword_6_0(), access
				.getCommaKeyword_6_2_0());

		// "do" unindents and indents
		c.setIndentation(access.getDoKeyword_7_0(), access.getDoKeyword_7_0());

		// "end" unindents
		c.setIndentation(null, access.getEndKeyword_8());

		c.setLinewrap().before(access.getDoKeyword_7_0());
		c.setLinewrap().after(access.getDoKeyword_7_0());

		c.setLinewrap().before(access.getEndKeyword_8());
		c.setLinewrap(2).after(access.getEndKeyword_8());
	}

	private void configureActionInputs(FormattingConfig c) {
		ActionElements access = f.getActionAccess();

		c.setNoSpace().before(access.getCommaKeyword_2_1_0());
		c.setNoSpace().before(f.getInputPatternAccess().getColonKeyword_0_1());
		c.setNoSpace().before(f.getInputPatternAccess().getCommaKeyword_3_0());
		c.setNoSpace().before(
				f.getInputPatternAccess().getLeftSquareBracketKeyword_1());
	}

	private void configureActionOutputs(FormattingConfig c) {
		ActionElements access = f.getActionAccess();

		c.setNoSpace().before(access.getCommaKeyword_4_1_0());
		c.setNoSpace().before(f.getOutputPatternAccess().getColonKeyword_0_1());
		c.setNoSpace().before(f.getOutputPatternAccess().getCommaKeyword_3_0());
		c.setNoSpace().before(
				f.getOutputPatternAccess().getLeftSquareBracketKeyword_1());
	}

	private void configureActorBody(FormattingConfig c) {
		ActorElements access = f.getActorAccess();

		c.setLinewrap(2).after(access.getColonKeyword_10());
		c.setIndentation(access.getColonKeyword_10(), access.getEndKeyword_14());

		c.setLinewrap(2).before(access.getEndKeyword_14());
		c.setLinewrap(2).after(access.getEndKeyword_14());
	}

	@Override
	protected void configureFormatting(FormattingConfig c) {
		f = (CalGrammarAccess) getGrammarAccess();

		c.setIndentationSpace("\t");

		// Tags
		c.setNoSpace().around(f.getTagAccess().getFullStopKeyword_1_0());

		// Imports
		c.setNoSpace().before(f.getImportAccess().getSemicolonKeyword_2());
		c.setLinewrap().after(f.getImportAccess().getSemicolonKeyword_2());
		c.setLinewrap(2).after(f.getActorAccess().getImportsAssignment_0());

		configureParameters(c);
		configurePorts(c);
		configureActorBody(c);

		configureStateVariable(c);

		configureFunction(c);

		configureAction(c);

		configureStatements(c);

		configureSchedule(c);

		configurePriorities(c);

		// Types
		configureIntType(c);
		configureUintType(c);

		configureIfExpression(c);
	}

	private void configureFunction(FormattingConfig c) {
		FunctionElements access = f.getFunctionAccess();

		c.setLinewrap(2).after(access.getEndKeyword_10());
	}

	private void configureIfExpression(FormattingConfig c) {
		IfExpressionElements access = f.getIfExpressionAccess();
		c.setIndentation(access.getThenKeyword_2(), access.getElseKeyword_4());
		c.setLinewrap().after(access.getThenKeyword_2());
		c.setIndentation(access.getElseKeyword_4(), access.getEndKeyword_6());
		c.setLinewrap().before(access.getElseKeyword_4());
		c.setLinewrap().after(access.getElseKeyword_4());
		c.setLinewrap().before(access.getEndKeyword_6());
	}

	private void configureIntType(FormattingConfig c) {
		IntTypeElements access = f.getIntTypeAccess();

		c.setNoSpace().before(access.getLeftParenthesisKeyword_1_0());
		c.setNoSpace().after(access.getLeftParenthesisKeyword_1_0());
		c.setNoSpace().after(access.getSizeKeyword_1_1());
		c.setNoSpace().after(access.getEqualsSignKeyword_1_2());
		c.setNoSpace().before(access.getRightParenthesisKeyword_1_4());

		c.setNoLinewrap().around(access.getLeftParenthesisKeyword_1_0());
		c.setNoLinewrap().around(access.getEqualsSignKeyword_1_2());
		c.setNoLinewrap().around(access.getRightParenthesisKeyword_1_4());
	}

	private void configureParameters(FormattingConfig c) {
		ActorElements access = f.getActorAccess();

		c.setIndentation(access.getLeftParenthesisKeyword_4(), access
				.getRightParenthesisKeyword_6());
		c.setNoSpace().after(access.getLeftParenthesisKeyword_4());
		c.setLinewrap().before(access.getParametersAssignment_5_0());
		c.setNoSpace().before(access.getCommaKeyword_5_1_0());
		c.setLinewrap().after(access.getCommaKeyword_5_1_0());
		c.setNoSpace().before(access.getRightParenthesisKeyword_6());
	}

	private void configurePorts(FormattingConfig c) {
		ActorElements access = f.getActorAccess();

		c.setNoLinewrap().around(access.getInputsAssignment_7_0());
		c.setNoLinewrap().around(access.getInputsAssignment_7_1_1());
		c.setNoLinewrap().around(access.getOutputsAssignment_9_0());
		c.setNoLinewrap().around(access.getOutputsAssignment_9_1_1());
		c.setNoSpace().before(access.getCommaKeyword_7_1_0());
	}

	private void configurePriorities(FormattingConfig c) {
		PriorityElements access = f.getPriorityAccess();

		c.setIndentation(access.getPriorityKeyword_0(), access
				.getEndKeyword_2());
		c.setLinewrap().after(access.getPriorityKeyword_0());
		c.setLinewrap(2).after(access.getEndKeyword_2());

		c.setNoSpace().before(f.getInequalityAccess().getSemicolonKeyword_2());
		c.setLinewrap().after(f.getInequalityAccess().getSemicolonKeyword_2());
	}

	private void configureSchedule(FormattingConfig c) {
		ScheduleElements access = f.getScheduleAccess();

		c.setIndentation(access.getScheduleKeyword_0(), access
				.getEndKeyword_5());
		c.setLinewrap().after(access.getColonKeyword_3());
		c.setLinewrap(2).after(access.getEndKeyword_5());

		c.setNoSpace().before(f.getTransitionAccess().getSemicolonKeyword_6());
		c.setLinewrap().after(f.getTransitionAccess().getSemicolonKeyword_6());
	}

	private void configureStatements(FormattingConfig c) {
		c.setLinewrap().after(f.getAssignAccess().getSemicolonKeyword_4());
		c.setNoSpace().before(f.getAssignAccess().getSemicolonKeyword_4());
	}

	private void configureStateVariable(FormattingConfig c) {
		StateVariableElements access = f.getStateVariableAccess();

		c.setNoSpace().before(access.getSemicolonKeyword_1());
		c.setLinewrap(2).after(access.getSemicolonKeyword_1());
	}

	private void configureUintType(FormattingConfig c) {
		UintTypeElements access = f.getUintTypeAccess();

		c.setNoSpace().before(access.getLeftParenthesisKeyword_1_0());
		c.setNoSpace().after(access.getLeftParenthesisKeyword_1_0());
		c.setNoSpace().after(access.getSizeKeyword_1_1());
		c.setNoSpace().after(access.getEqualsSignKeyword_1_2());
		c.setNoSpace().before(access.getRightParenthesisKeyword_1_4());

		c.setNoLinewrap().around(access.getLeftParenthesisKeyword_1_0());
		c.setNoLinewrap().around(access.getEqualsSignKeyword_1_2());
		c.setNoLinewrap().around(access.getRightParenthesisKeyword_1_4());
	}

	/**
	 * <pre>
	 * keyword
	 *   x,
	 *   y
	 * </pre>
	 * 
	 * @param c
	 * @param keyword
	 * @param comma
	 */
	private void keywordAndCommas(FormattingConfig c, Keyword keyword,
			Keyword comma) {
		// keyword indents
		c.setIndentation(keyword, null);

		// newline before and after keyword
		c.setLinewrap().before(keyword);
		c.setLinewrap().after(keyword);

		// no space before comma, new line after comma
		c.setLinewrap().after(comma);
		c.setNoSpace().before(comma);
	}
}
