/*
 * generated by Xtext 2.20.0
 */
package net.sf.orcc.cal.ide

import com.google.inject.Guice
import net.sf.orcc.cal.CalRuntimeModule
import net.sf.orcc.cal.CalStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CalIdeSetup extends CalStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CalRuntimeModule, new CalIdeModule))
	}
	
}
