<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cfg" nsURI="http://orcc.sf.net/model/2012/Cfg" nsPrefix="net.sf.orcc.cfg">
  <eClassifiers xsi:type="ecore:EClass" name="Cfg" eSuperTypes="../../net.sf.dftools.models/model/Graph.ecore#//Graph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="ecore:EClass Ir.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="ecore:EClass Ir.ecore#//Node"/>
  </eClassifiers>
</ecore:EPackage>
