<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="df"
    nsURI="http:///net/sf/orcc/df.ecore" nsPrefix="net.sf.orcc.df">
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="Ir.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="ecore:EClass Ir.ecore#//Port" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moC" eType="ecore:EClass MoC.ecore#//MoC"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="ecore:EClass Ir.ecore#//Port" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass Ir.ecore#//Var" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="ecore:EClass Ir.ecore#//Var" containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
