<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moc" nsURI="http://orcc.sf.net/model/2011/MoC" nsPrefix="net.sf.orcc.moc">
  <eClassifiers xsi:type="ecore:EClass" name="MoC" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CSDFMoC" eSuperTypes="#//MoC">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPattern" eType="ecore:EClass Df.ecore#//Pattern"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfPhases" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPattern" eType="ecore:EClass Df.ecore#//Pattern"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" upperBound="-1"
        eType="#//Invocation" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delayPattern" eType="ecore:EClass Df.ecore#//Pattern"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DPNMoC" eSuperTypes="#//MoC"/>
  <eClassifiers xsi:type="ecore:EClass" name="KPNMoC" eSuperTypes="#//MoC"/>
  <eClassifiers xsi:type="ecore:EClass" name="QSDFMoC" eSuperTypes="#//MoC"/>
  <eClassifiers xsi:type="ecore:EClass" name="SDFMoC" eSuperTypes="#//CSDFMoC"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="ecore:EClass Df.ecore#//Action"/>
  </eClassifiers>
</ecore:EPackage>
